### ISSUE TITLE
RuntimeError, tensor size mismatch

### ISSUE THREAD

**Issue by Nighteye** [JannerM/intrinsics-network#4]
I get the following error when running the decomposer:

Traceback (most recent call last):
  File "decomposer.py", line 62, in <module>
    train_losses = trainer.train()
  File "/home/nietog/Projects/intrinsics-network/pipeline/DecomposerTrainer.py", line 42, in train
    err = self.__epoch()
  File "/home/nietog/Projects/intrinsics-network/pipeline/DecomposerTrainer.py", line 30, in __epoch
    loss.backward()
  File "/home/nietog/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/nietog/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/home/nietog/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/nietog/anaconda3/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 454, in backward
    print(grad_output.clone().masked_fill_(mask, 0))
RuntimeError: The expanded size of the tensor (1) must match the existing size (32) at non-singleton dimension 1. at /opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generic/THCTensor.c:323

Any idea where it comes from? Thanks in advance.

**Comment by jannerm** [comment]
My first thought was that this was the same as the other size mismatch error and would be resolved by adding the `keepdim` flags in all the relevant places. It looks like it's a different issue though.

In the meantime, are you able to use PyTorch 0.1.12?

**Comment by Nighteye** [comment]
Also I managed to run the shader with pytorch version 0.3.0, despite the warnings about some mismatched tensor sizes. Those warnings might be related to the reason why the decomposer fails to work. I will try to investigate why I have time.
It seems to work fine with PyTorch 0.1.12! Thank you!

**Comment by FangYang970206** [comment]
@Nighteye   I had the same error before. According to #3 ，I replace the code `reflectance[mask] = 0`,`normed[mask] = 0`and`depth[mask[:,0]] = 0` in Decomposer.py  by `reflectance = reflectance*(mask==1).float()`,`normed = normed*(mask==1).float()`and `depth = depth*(mask[:,0].unsqueeze(1)==1).float()`. And the decomposer.py can run in pytorch version 0.3.0.

**Comment by Liforam** [comment]
I get the following error when running the decomposer:

Traceback (most recent call last):
  File "decomposer.py", line 59, in <module>
    val_losses = pipeline.visualize_decomposer(model, val_loader, args.save_path, epoch)
  File "/home/xuwh/xu/intrinsics-network-master/pipeline/visualization.py", line 122, in visualize_decomposer
    refl_pred, depth_pred, shape_pred, lights_pred = model.forward(inp, mask)
  File "/home/xuwh/xu/intrinsics-network-master/models/Decomposer.py", line 101, in forward
    normed = primitives.normalize(clamped)
  File "/home/xuwh/xu/intrinsics-network-master/models/primitives.py", line 41, in normalize
    normed = normals / (magnitude + 1e-6)
RuntimeError: The size of tensor a (3) must match the size of tensor b (60) at non-singleton dimension 1

Any solution? Thanks
@FangYang970206  @Nighteye

**Comment by FangYang970206** [comment]
@Liforam maybe you should add the keepdim in the first line of primitives.normal function. Like this 'magnitude = torch.pow(normals, 2).sum(1,keepdim=True)'

**Comment by FangYang970206** [comment]
@Liforam maybe you should add the keepdim in the first line of primitives.normal function. Like this `magnitude = torch.pow(normals, 2).sum(1,keepdim=True)`

**Comment by Liforam** [comment]
Thank you! And it seems to work well with Pytorch version 0.1.12 as  @Nighteye  said.

**Comment by ava-YangL** [comment]
I add the keepdim in 
`magnitude = torch.pow(normals, 2).sum(1,keepdim=True)`
```
    if dim == 4:
        mask = torch.pow(vector,2).sum(1,keepdim=True) > .01
        mask = mask.repeat(1,3,1,1)
    elif dim == 3:
        mask = torch.pow(vector,2).sum(0,keepdim=True) > .01
        mask = mask.repeat(3,1,1)
    else:
```
and 
 replace the code 
```
reflectance[mask] = 0
normed[mask] = 0
depth[mask[:,0]] = 0
```
To 
```
 reflectance = reflectance*(mask==1).float()
normed = normed*(mask==1).float()
 depth = depth*(mask[:,0].unsqueeze(1)==1).float()
```
but get the following error
```
Traceback (most recent call last):
  File "decomposer.py", line 62, in <module>
    train_losses = trainer.train()
  File "/data/yl/code/3D/1/intrinsics-network-master/pipeline/DecomposerTrainer.py", line 42, in train
    err = self.__epoch()
  File "/data/yl/code/3D/1/intrinsics-network-master/pipeline/DecomposerTrainer.py", line 26, in __epoch
    depth_loss = self.criterion(depth_pred, depth_targ)
  File "/data/yl/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yl/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 372, in forward
    return F.mse_loss(input, target, size_average=self.size_average, reduce=self.reduce)
  File "/data/yl/software/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1569, in mse_loss
    input, target, size_average, reduce)
  File "/data/yl/software/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1537, in _pointwise_loss
    return lambd_optimized(input, target, size_average, reduce)
RuntimeError: input and target shapes do not match: input [32 x 1 x 256 x 256], target [32 x 256 x 256] at /pytorch/aten/src/THCUNN/generic/MSECriterion.cu:15

```

Any idea where it comes from? Thanks a lot for any  advives @FangYang970206 @Liforam @Nighteye 
I use pytorch0.4.0 and python3.6~

**Comment by jannerm** [comment]
Without running it myself with Python 3.6, it looks like `depth_pred` and `depth_targ` do have the same number of elements, so this should do the trick:

`depth_targ = depth_targ.unsqueeze(1)`

**Comment by ava-YangL** [comment]
Thank you very much! @JannerM

**Comment by akshay-iyer** [comment]
With torch 0.1.12.post2, running shader.py gives AttributeError: module 'torch.nn' has no attribute 'ModuleDict' because indeed dir(torch.nn) does not have ModuleDict

Did anyone else face this problem?

**Comment by jannerm** [comment]
Could you post the full error trace to help me reproduce this?

**Comment by akshay-iyer** [comment]
I am using Python3 and used 2to3(..) to convert the files to be compatible with Python3 

Please find the error trace:
Traceback (most recent call last):
  File "shader.py", line 4, in <module>
    import models, pipeline
  File "/home/abiyer/intrinsics-network-master/pipeline/__init__.py", line 8, in <module>
    from .visualization import *
  File "/home/abiyer/intrinsics-network-master/pipeline/visualization.py", line 1, in <module>
    import os, math, torch, torch.nn as nn, torchvision.utils, numpy as np, scipy.misc, pdb
  File "/home/abiyer/rin_env/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/abiyer/rin_env/lib/python3.6/site-packages/torchvision/models/__init__.py", line 10, in <module>
    from . import segmentation
  File "/home/abiyer/rin_env/lib/python3.6/site-packages/torchvision/models/segmentation/__init__.py", line 1, in <module>
    from .segmentation import *
  File "/home/abiyer/rin_env/lib/python3.6/site-packages/torchvision/models/segmentation/segmentation.py", line 1, in <module>
    from .._utils import IntermediateLayerGetter
  File "/home/abiyer/rin_env/lib/python3.6/site-packages/torchvision/models/_utils.py", line 7, in <module>
    class IntermediateLayerGetter(nn.ModuleDict):
AttributeError: module 'torch.nn' has no attribute 'ModuleDict'

**Comment by jannerm** [comment]
This looks like a mismatch between the torch and torchvision versions. Try `pip install torchvision==0.1.9`.

**Comment by akshay-iyer** [comment]
Thanks it did work with this

**Comment by akshay-iyer** [comment]
Hi, did anyone face an issue in the decomposer predicting an incorrect output?
After training for 500 epochs, my reflectance loss is similar to that in the paper although the reflectance image is poor. However my shape and lights loss is an order of magnitude higher and the lights loss does not seem to converge.

Anyone faced anything similar?

Cheers.

**Comment by jannerm** [comment]
Have you checked whether this issue also exists with python 2.7? I am not sure what changes 2to3 makes to the codebase.
